/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  images: {
    domains: [
      'images.barteryard.club',
      'assets.website-files.com',
      'd13e14gtps4iwl.cloudfront.net',
      'tokenrunners.com',
      'bl0x.xyz',
      'images.flovatar.com',
      'www.flowns.org',
      'i.imgur.com',
      'www.dimensionx.com',
      'miro.medium.com',
      'www.fridgemagnet.xyz',
      'flowverse-mystery-pass.s3.filebase.com',
      'warehouse.genies.com',
      'gateway.pinata.cloud',
      's3.us-west-2.amazonaws.com',
      'storage.googleapis.com',
      'frightclub.niftory.com',
      'goatedgoats.com',
      'nftstorage.link',
      'inceptionanimals.com',
      'otmnft-jj.s3.amazonaws.com',
      'mint-store-metadata.s3.us-east-2.amazonaws.com',
      'swaychain.com',
      'static.mono.fun',
      'rockpeaksassets.s3.amazonaws.com',
      'nbatopshot.com',
      'pbs.twimg.com',
      'rcrdshp-happyfox-assets.s3.amazonaws.com',
      'eqmusic.io',
      'www.snkrhud.com',
      'sequel.space',
      'sportsicon.com',
      'storage.googleapis.com',
      'ipfs.tenzingai.com',
      'cdn.solarpups.com',
      'basicbeasts.mypinata.cloud',
      'www.skyharbor.app',
      'raw.githubusercontent.com',
      'tunegonft.com',
      'nftstorage.link',
      'trart.io',
      'static.tunegonft.com',
      'tunegonft.com',
      'media.gigantik.io',
      'pbs.twimg.com',
      'ipfs.tenzingai.com',
      'mint-store-metadata.s3.us-east-2.amazonaws.com',
      'raw.githubusercontent.com',
      'play.zeedz.io',
      'd3w5a827wx4ops.cloudfront.net'
    ],
    dangerouslyAllowSVG: true,
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;"
  }
}

module.exports = nextConfig
