import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import useSWR, { useSWRConfig } from 'swr'
import { getLinkStatus, getNFTCatalog } from '../flow/scripts'
import { badlink, setupAccount, relink } from '../flow/transactions'
import ErrorPage from './ErrorPage'
import { useRecoilState } from "recoil"
import { SpinnerCircular } from 'spinners-react'
import {
  transactionInProgressState,
  transactionStatusState
} from "../lib/atoms"
import * as fcl from "@onflow/fcl"
import { ArrowCircleDownIcon, ArrowCircleLeftIcon, ArrowCircleRightIcon } from '@heroicons/react/outline'

const catalogFetcher = async (funcName) => {
  return await getNFTCatalog()
}

const linkStatusFetcher = async (funcName, account, catalog) => {
  return await getLinkStatus(account, catalog)
}

// There are some records with duplicate contractName
// contracts with duplicate contractName can't be imported in
// the same cadence code, so we just handle the first one
const sortObject = o => Object.keys(o).sort().reduce((r, k) => (r[k] = o[k], r), {})

const classNames = (...classes) => {
  return classes.filter(Boolean).join(' ')
}

const filterCatalog = (catalog) => {
  let cleaned = {}
  let contractNames = {}
  for (const [catalogName, metadata] of Object.entries(catalog)) {
    if (!contractNames[metadata.contractName]) {
      contractNames[metadata.contractName] = true
      cleaned[catalogName] = metadata
    }
  }
  return sortObject(cleaned)
}

export default function Home(props) {
  const [transactionInProgress, setTransactionInProgress] = useRecoilState(transactionInProgressState)
  const [, setTransactionStatus] = useRecoilState(transactionStatusState)
  const { mutate } = useSWRConfig()

  const user = props.user
  const account = user && user.loggedIn ? user.addr : null

  const { data: catalogData, error: catalogError } = useSWR(["catalogFetcher"], catalogFetcher)
  const [catalog, setCatalog] = useState(null)
  const [showCorrectlyLinked, setShowCorrectlyLinked] = useState(false)
  const [linkStatus, setLinkStatus] = useState(null)

  useEffect(() => {
    if (catalogData) {
      setCatalog(filterCatalog(catalogData))
    }
  }, [catalogData])

  const { data: statusData, error: statusError } = useSWR(
    (catalog && account) ? ["linkStatusFetcher", account, catalog] : null, linkStatusFetcher)

  useEffect(() => {
    if (statusData) { setLinkStatus(statusData) }
  }, [statusData])

  if (catalogError) {
    return <ErrorPage code={catalogError.statusCode} title={"Get NFTCatalog Failed"} detail={"Please check you network status and try again"} />
  }

  if (statusError) {
    return <ErrorPage code={statusError.statusCode} title={"Get Link Status Failed"} detail={"Please check you network status and try again"} />
  }

  return (
    <div className="container mx-auto max-w-[920px] min-w-[380px] px-6">
      <Head>
        <title>Link | NFT catalog link tool</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!account ?
        <div className="w-full h-[300px] flex flex-col gap-y-8 items-center justify-center">
          <label className="font-flow font-bold text-4xl sm:text-5xl">Explore <span className='text-emerald'>#onFlow</span></label>
          <label className="-mt-4 font-flow font-bold text-4xl sm:text-5xl">With Right 🔗<span className='text-emerald'>Link</span></label>
          <button
            type="button"
            className="mt-3 h-12 px-6 text-base rounded-2xl font-flow font-semibold shadow-sm text-black bg-emerald hover:bg-emerald-dark"
            onClick={fcl.logIn}
          >
            <label>Connect Wallet</label>
          </button>
        </div>
        : null
      }
      {
        account && linkStatus ?
          <div>
            {linkStatus.bad.length > 0 ?
              <div className="mb-8 flex flex-col gap-y-3 w-full">
                <label className="font-flow font-bold text-2xl">Not Correctly Linked</label>
                {
                  linkStatus.bad.map((name) => {
                    const metadata = catalog[name]
                    const imageURL = metadata.collectionDisplay.squareImage.file.url
                    return (
                      <div key={name} className="flex gap-x-3 items-center justify-between w-full px-4 py-4 rounded-3xl 
            ring-1 ring-black ring-opacity-10 overflow-hidden bg-white">
                        <div className='shrink truncate flex gap-x-2 items-center'>
                          <div className="h-[40px] w-[40px] shrink-0 relative rounded-xl overflow-hidden bg-emerald">
                            <Image src={`/api/imageproxy?url=${encodeURIComponent(imageURL)}`} alt="" layout="fill" objectFit="cover" />
                          </div>
                          <label className="shrink font-flow font-bold text-lg truncate">{name}</label>
                        </div>

                        <button
                          className={
                            classNames(
                              transactionInProgress ? "bg-emerald-light text-gray-500" : "hover:bg-emerald-dark bg-emerald text-black",
                              "shrink-0 truncate font-flow text-base shadow-sm font-bold w-[100px] rounded-full px-3 py-2 leading-5"
                            )}
                          disabled={transactionInProgress}
                          onClick={async () => {
                            await relink(metadata, setTransactionInProgress, setTransactionStatus)
                            mutate(["linkStatusFetcher", account, catalog])
                          }}
                        >
                          RELINK
                        </button>
                      </div>
                    )
                  })
                }
              </div>
              : null
            }
            {linkStatus.good.length > 0 ?
              <div className="mb-8 flex flex-col gap-y-3 w-full">
                <button 
                  className="flex justify-between"
                  onClick={() => {
                    setShowCorrectlyLinked(!showCorrectlyLinked)
                  }}
                >
                  <label className="block font-flow font-bold text-2xl">Correctly Linked</label>
                  {!showCorrectlyLinked ?
                  <ArrowCircleRightIcon className="text-emerald" width={32} height={32} /> :
                  <ArrowCircleDownIcon className="text-emerald" width={32} height={32} />
                  }
                </button>
                { showCorrectlyLinked ?
                  linkStatus.good.map((name) => {
                    const metadata = catalog[name]
                    const imageURL = metadata.collectionDisplay.squareImage.file.url
                    return (
                      <div key={name} className="flex gap-x-3 items-center justify-between w-full px-4 py-4 rounded-3xl 
            ring-1 ring-black ring-opacity-10 overflow-hidden bg-white">
                        <div className='shrink truncate flex gap-x-2 items-center'>
                          <div className="h-[40px] w-[40px] shrink-0 relative rounded-xl overflow-hidden bg-emerald">
                            <Image src={`/api/imageproxy?url=${encodeURIComponent(imageURL)}`} alt="" layout="fill" objectFit="cover" />
                          </div>
                          <label className="shrink font-flow font-bold text-lg truncate">{name}</label>
                        </div>
                      </div>
                    )
                  })
                : null}
              </div>
              : null
            }
            {linkStatus.unlinked.length > 0 ?
              <div className="mb-8 flex flex-col gap-y-3 w-full">
                <label className="block font-flow font-bold text-2xl">Not Linked Yet</label>
                {
                  linkStatus.unlinked.map((name) => {
                    const metadata = catalog[name]
                    const imageURL = metadata.collectionDisplay.squareImage.file.url
                    return (
                      <div key={name} className="w-full flex gap-x-3 items-center justify-between px-4 py-4 rounded-3xl 
            ring-1 ring-black ring-opacity-10 bg-white overflow-hidden">

                        <div className='shrink truncate w-full flex gap-x-2 items-center'>
                          <div className="h-[40px] w-[40px] shrink-0 relative rounded-xl overflow-hidden bg-emerald">
                            <Image src={`/api/imageproxy?url=${encodeURIComponent(imageURL)}`} alt="" layout="fill" objectFit="cover" />
                          </div>
                          <label className="shrink font-flow font-bold text-lg truncate">{name}</label>
                        </div>

                        <button
                          className="shrink-0 truncate font-flow text-base
                        text-black shadow-sm font-bold w-[100px]
                        hover:bg-emerald-dark
                        bg-emerald rounded-full px-3 py-2 leading-5"
                          onClick={async () => {
                            await setupAccount(metadata, setTransactionInProgress, setTransactionStatus)
                            mutate(["linkStatusFetcher", account, catalog])
                          }}
                        >
                          SETUP
                        </button>

                        {/* TESTONLY */}
                        {/* <button
                          className="shrink-0 truncate font-flow text-base
                        text-black shadow-sm font-bold w-[100px]
                        hover:bg-emerald-dark
                        bg-emerald rounded-full px-3 py-2 leading-5"
                          onClick={async () => {
                            await badlink(metadata, setTransactionInProgress, setTransactionStatus)
                          }}
                        >
                          BADLINK
                        </button> */}
                      </div>
                    )
                  })
                }
              </div>
              : null}

          </div>
          : <>
            {account ?
              <div className="flex h-[200px] mt-10 justify-center">
                <SpinnerCircular size={50} thickness={180} speed={100} color="#38E8C6" secondaryColor="#e2e8f0" />
              </div>
              : null}
          </>
      }
    </div>
  )
}
